#!/bin/bash
#
# MPICH on Tofu Shell Environment
#
if [ X$MPICH_HOME != X ]; then
# MPICH_HOME is defined
.  ${MPICH_HOME}/lib/mpich.env
   if [ -f $MPICH_HOME/lib/libutf.so ]; then
      export LD_LIBRARY_PATH=$MPICH_HOME/lib:$LD_LIBRARY_PATH
   else
      echo "Cannot find an MPICH-Tofu library"
      exit -1
   fi 
elif [ X$HOME/mpich-tofu != X ]; then
# $HOME/mpich-tofu/ is defined
.  ${HOME}/mpich-tofu/lib/mpich.env
   if [ -f $HOME/mpich-tofu/lib/libutf.so ]; then
      export LD_LIBRARY_PATH=$HOME/mpich-tofu/lib:$LD_LIBRARY_PATH
   else
      echo "Cannot find an MPICH-Tofu library"
      exit -1
   fi
MPICH_HOME=${HOME}/mpich-tofu
else
    echo "Cannot find MPICH runtime environment."
    echo "  Please define the MPICH_HOME shell environment."
    exit -1
fi

if [ X$UTF_BG_LOAD != X ]; then
    export LD_PRELOAD="$MPICH_HOME/lib/libutf.so $MPICH_HOME/lib/libmpi_vbg.so $MPICH_HOME/lib/libmpi.so /usr/lib/FJSVtcs/ple/lib64/libpmix.so $LD_PRELOAD"
else
    export LD_PRELOAD="$MPICH_HOME/lib/libutf.so $MPICH_HOME/lib/libmpi.so /usr/lib/FJSVtcs/ple/lib64/libpmix.so $LD_PRELOAD"
fi
export LD_LIBRARY_PATH=$MPICH_HOME/lib:$LD_LIBRARY_PATH

if [ X$MPICH_TOFU_SHOW_PARAMS != X ]; then
   echo "CWD = " `pwd`
   echo "mpich_exec = " `which mpich_exec`
   echo "LD_PRELOAD = " $LD_PRELOAD
   echo "LD_LIBRARY_PATH = " $LD_LIBRARY_PATH
   echo "TOFU_NAMED_AV = " $TOFU_NAMED_AV
   echo "UTF_MSGMODE   = " $UTF_MSGMODE "(0: Eager, 1: Rendezous)"
   echo "UTF_TRANSMODE = " $UTF_TRANSMODE "(0: Chained, 1: Aggressive)"
   echo "UTF_DEBUG     = " $UTF_DEBUG
   echo "MPIR_CVAR_CH4_OFI_ENABLE_TAGGED      = " $MPIR_CVAR_CH4_OFI_ENABLE_TAGGED
   echo "MPIR_CVAR_CH4_OFI_EAGER_MAX_MSG_SIZE = " $MPIR_CVAR_CH4_OFI_EAGER_MAX_MSG_SIZE
   echo "MPIR_CVAR_REDUCE_INTRA_ALGORITHM     = " $MPIR_CVAR_REDUCE_INTRA_ALGORITHM
   echo "MPIR_CVAR_ALLREDUCE_INTRA_ALGORITHM  = " $MPIR_CVAR_ALLREDUCE_INTRA_ALGORITHM
   echo "MPIR_CVAR_ALLTOALL_INTRA_ALGORITHM   = " $MPIR_CVAR_ALLTOALL_INTRA_ALGORITHM
   echo "MPIR_CVAR_CH4_OFI_EAGER_MAX_MSG_SIZE = " $MPIR_CVAR_CH4_OFI_EAGER_MAX_MSG_SIZE
   echo "MPIR_CVAR_CH4_OFI_SHORT_SEND_SIZE    = " $MPIR_CVAR_CH4_OFI_SHORT_SEND_SIZE
fi

# Others

mpiexec $*
