#define PMI2_Abort                                              PMI2_Abort
#define PMI2_Finalize                                           PMI2_Finalize
#define PMI2_Info_GetJobAttr                                    PMI2_Info_GetJobAttr
#define PMI2_Info_GetJobAttrIntArray                            PMI2_Info_GetJobAttrIntArray
#define PMI2_Info_GetNodeAttr                                   PMI2_Info_GetNodeAttr
#define PMI2_Info_GetNodeAttrIntArray                           PMI2_Info_GetNodeAttrIntArray
#define PMI2_Info_GetSize                                       PMI2_Info_GetSize
#define PMI2_Info_PutNodeAttr                                   PMI2_Info_PutNodeAttr
#define PMI2_Init                                               PMI2_Init
#define PMI2_Initialized                                        PMI2_Initialized
#define PMI2_Job_Connect                                        PMI2_Job_Connect
#define PMI2_Job_Disconnect                                     PMI2_Job_Disconnect
#define PMI2_Job_GetId                                          PMI2_Job_GetId
#define PMI2_Job_GetRank                                        PMI2_Job_GetRank
#define PMI2_Job_Spawn                                          PMI2_Job_Spawn
#define PMI2_KVS_Fence                                          PMI2_KVS_Fence
#define PMI2_KVS_Get                                            PMI2_KVS_Get
#define PMI2_KVS_Put                                            PMI2_KVS_Put
#define PMI2_Nameserv_lookup                                    PMI2_Nameserv_lookup
#define PMI2_Nameserv_publish                                   PMI2_Nameserv_publish
#define PMI2_Nameserv_unpublish                                 PMI2_Nameserv_unpublish
#define PMI_Abort                                               PMI_Abort
#define PMI_Args_to_keyval                                      PMI_Args_to_keyval
#define PMI_Barrier                                             PMI_Barrier
#define PMI_Finalize                                            PMI_Finalize
#define PMI_Free_keyvals                                        PMI_Free_keyvals
#define PMI_Get_appnum                                          PMI_Get_appnum
#define PMI_Get_clique_ranks                                    PMI_Get_clique_ranks
#define PMI_Get_clique_size                                     PMI_Get_clique_size
#define PMI_Get_id                                              PMI_Get_id
#define PMI_Get_id_length_max                                   PMI_Get_id_length_max
#define PMI_Get_kvs_domain_id                                   PMI_Get_kvs_domain_id
#define PMI_Get_options                                         PMI_Get_options
#define PMI_Get_rank                                            PMI_Get_rank
#define PMI_Get_size                                            PMI_Get_size
#define PMI_Get_universe_size                                   PMI_Get_universe_size
#define PMI_Init                                                PMI_Init
#define PMI_Initialized                                         PMI_Initialized
#define PMI_KVS_Commit                                          PMI_KVS_Commit
#define PMI_KVS_Create                                          PMI_KVS_Create
#define PMI_KVS_Destroy                                         PMI_KVS_Destroy
#define PMI_KVS_Get                                             PMI_KVS_Get
#define PMI_KVS_Get_key_length_max                              PMI_KVS_Get_key_length_max
#define PMI_KVS_Get_my_name                                     PMI_KVS_Get_my_name
#define PMI_KVS_Get_name_length_max                             PMI_KVS_Get_name_length_max
#define PMI_KVS_Get_value_length_max                            PMI_KVS_Get_value_length_max
#define PMI_KVS_Iter_first                                      PMI_KVS_Iter_first
#define PMI_KVS_Iter_next                                       PMI_KVS_Iter_next
#define PMI_KVS_Put                                             PMI_KVS_Put
#define PMI_Lookup_name                                         PMI_Lookup_name
#define PMI_Parse_option                                        PMI_Parse_option
#define PMI_Publish_name                                        PMI_Publish_name
#define PMI_Spawn_multiple                                      PMI_Spawn_multiple
#define PMI_Unpublish_name                                      PMI_Unpublish_name
#define PMIx_Abort                                              PMIx_Abort
#define PMIx_Allocation_request_nb                              PMIx_Allocation_request_nb
#define PMIx_Alloc_directive_string                             PMIx_Alloc_directive_string
#define pmix_argv_append                                        pmix_argv_append
#define pmix_argv_append_nosize                                 pmix_argv_append_nosize
#define pmix_argv_append_unique_nosize                          pmix_argv_append_unique_nosize
#define pmix_argv_copy                                          pmix_argv_copy
#define pmix_argv_count                                         pmix_argv_count
#define pmix_argv_delete                                        pmix_argv_delete
#define pmix_argv_free                                          pmix_argv_free
#define pmix_argv_insert                                        pmix_argv_insert
#define pmix_argv_insert_element                                pmix_argv_insert_element
#define pmix_argv_join                                          pmix_argv_join
#define pmix_argv_join_range                                    pmix_argv_join_range
#define pmix_argv_len                                           pmix_argv_len
#define pmix_argv_prepend_nosize                                pmix_argv_prepend_nosize
#define pmix_argv_split                                         pmix_argv_split
#define pmix_argv_split_with_empty                              pmix_argv_split_with_empty
#define pmix_asprintf                                           pmix_asprintf
#define pmix_basename                                           pmix_basename
#define pmix_bfrop_base_copy_persist                            pmix_bfrop_base_copy_persist
#define pmix_bfrop_base_select                                  pmix_bfrop_base_select
#define pmix_bfrop_buffer_extend                                pmix_bfrop_buffer_extend
#define pmix_bfrop_get_data_type                                pmix_bfrop_get_data_type
#define pmix_bfrops_base_assign_module                          pmix_bfrops_base_assign_module
#define pmix_bfrops_base_copy                                   pmix_bfrops_base_copy
#define pmix_bfrops_base_copy_app                               pmix_bfrops_base_copy_app
#define pmix_bfrops_base_copy_array                             pmix_bfrops_base_copy_array
#define pmix_bfrops_base_copy_bo                                pmix_bfrops_base_copy_bo
#define pmix_bfrops_base_copy_buf                               pmix_bfrops_base_copy_buf
#define pmix_bfrops_base_copy_darray                            pmix_bfrops_base_copy_darray
#define pmix_bfrops_base_copy_info                              pmix_bfrops_base_copy_info
#define pmix_bfrops_base_copy_kval                              pmix_bfrops_base_copy_kval
#define pmix_bfrops_base_copy_modex                             pmix_bfrops_base_copy_modex
#define pmix_bfrops_base_copy_payload                           pmix_bfrops_base_copy_payload
#define pmix_bfrops_base_copy_pdata                             pmix_bfrops_base_copy_pdata
#define pmix_bfrops_base_copy_pinfo                             pmix_bfrops_base_copy_pinfo
#define pmix_bfrops_base_copy_proc                              pmix_bfrops_base_copy_proc
#define pmix_bfrops_base_copy_query                             pmix_bfrops_base_copy_query
#define pmix_bfrops_base_copy_string                            pmix_bfrops_base_copy_string
#define pmix_bfrops_base_copy_value                             pmix_bfrops_base_copy_value
#define pmix_bfrops_base_data_type_string                       pmix_bfrops_base_data_type_string
#define pmix_bfrops_base_framework                              pmix_bfrops_base_framework
#define pmix_bfrops_base_get_available_modules                  pmix_bfrops_base_get_available_modules
#define pmix_bfrops_base_output                                 pmix_bfrops_base_output
#define pmix_bfrops_base_pack                                   pmix_bfrops_base_pack
#define pmix_bfrops_base_pack_alloc_directive                   pmix_bfrops_base_pack_alloc_directive
#define pmix_bfrops_base_pack_app                               pmix_bfrops_base_pack_app
#define pmix_bfrops_base_pack_array                             pmix_bfrops_base_pack_array
#define pmix_bfrops_base_pack_bo                                pmix_bfrops_base_pack_bo
#define pmix_bfrops_base_pack_bool                              pmix_bfrops_base_pack_bool
#define pmix_bfrops_base_pack_buf                               pmix_bfrops_base_pack_buf
#define pmix_bfrops_base_pack_buffer                            pmix_bfrops_base_pack_buffer
#define pmix_bfrops_base_pack_byte                              pmix_bfrops_base_pack_byte
#define pmix_bfrops_base_pack_cmd                               pmix_bfrops_base_pack_cmd
#define pmix_bfrops_base_pack_darray                            pmix_bfrops_base_pack_darray
#define pmix_bfrops_base_pack_datatype                          pmix_bfrops_base_pack_datatype
#define pmix_bfrops_base_pack_double                            pmix_bfrops_base_pack_double
#define pmix_bfrops_base_pack_float                             pmix_bfrops_base_pack_float
#define pmix_bfrops_base_pack_info                              pmix_bfrops_base_pack_info
#define pmix_bfrops_base_pack_info_directives                   pmix_bfrops_base_pack_info_directives
#define pmix_bfrops_base_pack_int                               pmix_bfrops_base_pack_int
#define pmix_bfrops_base_pack_int16                             pmix_bfrops_base_pack_int16
#define pmix_bfrops_base_pack_int32                             pmix_bfrops_base_pack_int32
#define pmix_bfrops_base_pack_int64                             pmix_bfrops_base_pack_int64
#define pmix_bfrops_base_pack_kval                              pmix_bfrops_base_pack_kval
#define pmix_bfrops_base_pack_modex                             pmix_bfrops_base_pack_modex
#define pmix_bfrops_base_pack_pdata                             pmix_bfrops_base_pack_pdata
#define pmix_bfrops_base_pack_persist                           pmix_bfrops_base_pack_persist
#define pmix_bfrops_base_pack_pid                               pmix_bfrops_base_pack_pid
#define pmix_bfrops_base_pack_pinfo                             pmix_bfrops_base_pack_pinfo
#define pmix_bfrops_base_pack_proc                              pmix_bfrops_base_pack_proc
#define pmix_bfrops_base_pack_pstate                            pmix_bfrops_base_pack_pstate
#define pmix_bfrops_base_pack_ptr                               pmix_bfrops_base_pack_ptr
#define pmix_bfrops_base_pack_query                             pmix_bfrops_base_pack_query
#define pmix_bfrops_base_pack_range                             pmix_bfrops_base_pack_range
#define pmix_bfrops_base_pack_rank                              pmix_bfrops_base_pack_rank
#define pmix_bfrops_base_pack_scope                             pmix_bfrops_base_pack_scope
#define pmix_bfrops_base_pack_sizet                             pmix_bfrops_base_pack_sizet
#define pmix_bfrops_base_pack_status                            pmix_bfrops_base_pack_status
#define pmix_bfrops_base_pack_string                            pmix_bfrops_base_pack_string
#define pmix_bfrops_base_pack_time                              pmix_bfrops_base_pack_time
#define pmix_bfrops_base_pack_timeval                           pmix_bfrops_base_pack_timeval
#define pmix_bfrops_base_pack_val                               pmix_bfrops_base_pack_val
#define pmix_bfrops_base_pack_value                             pmix_bfrops_base_pack_value
#define pmix_bfrops_base_print                                  pmix_bfrops_base_print
#define pmix_bfrops_base_print_alloc_directive                  pmix_bfrops_base_print_alloc_directive
#define pmix_bfrops_base_print_app                              pmix_bfrops_base_print_app
#define pmix_bfrops_base_print_array                            pmix_bfrops_base_print_array
#define pmix_bfrops_base_print_bo                               pmix_bfrops_base_print_bo
#define pmix_bfrops_base_print_bool                             pmix_bfrops_base_print_bool
#define pmix_bfrops_base_print_buf                              pmix_bfrops_base_print_buf
#define pmix_bfrops_base_print_byte                             pmix_bfrops_base_print_byte
#define pmix_bfrops_base_print_cmd                              pmix_bfrops_base_print_cmd
#define pmix_bfrops_base_print_darray                           pmix_bfrops_base_print_darray
#define pmix_bfrops_base_print_datatype                         pmix_bfrops_base_print_datatype
#define pmix_bfrops_base_print_double                           pmix_bfrops_base_print_double
#define pmix_bfrops_base_print_float                            pmix_bfrops_base_print_float
#define pmix_bfrops_base_print_info                             pmix_bfrops_base_print_info
#define pmix_bfrops_base_print_info_directives                  pmix_bfrops_base_print_info_directives
#define pmix_bfrops_base_print_int                              pmix_bfrops_base_print_int
#define pmix_bfrops_base_print_int16                            pmix_bfrops_base_print_int16
#define pmix_bfrops_base_print_int32                            pmix_bfrops_base_print_int32
#define pmix_bfrops_base_print_int64                            pmix_bfrops_base_print_int64
#define pmix_bfrops_base_print_int8                             pmix_bfrops_base_print_int8
#define pmix_bfrops_base_print_kval                             pmix_bfrops_base_print_kval
#define pmix_bfrops_base_print_modex                            pmix_bfrops_base_print_modex
#define pmix_bfrops_base_print_pdata                            pmix_bfrops_base_print_pdata
#define pmix_bfrops_base_print_persist                          pmix_bfrops_base_print_persist
#define pmix_bfrops_base_print_pid                              pmix_bfrops_base_print_pid
#define pmix_bfrops_base_print_pinfo                            pmix_bfrops_base_print_pinfo
#define pmix_bfrops_base_print_proc                             pmix_bfrops_base_print_proc
#define pmix_bfrops_base_print_pstate                           pmix_bfrops_base_print_pstate
#define pmix_bfrops_base_print_ptr                              pmix_bfrops_base_print_ptr
#define pmix_bfrops_base_print_query                            pmix_bfrops_base_print_query
#define pmix_bfrops_base_print_range                            pmix_bfrops_base_print_range
#define pmix_bfrops_base_print_rank                             pmix_bfrops_base_print_rank
#define pmix_bfrops_base_print_scope                            pmix_bfrops_base_print_scope
#define pmix_bfrops_base_print_size                             pmix_bfrops_base_print_size
#define pmix_bfrops_base_print_status                           pmix_bfrops_base_print_status
#define pmix_bfrops_base_print_string                           pmix_bfrops_base_print_string
#define pmix_bfrops_base_print_time                             pmix_bfrops_base_print_time
#define pmix_bfrops_base_print_timeval                          pmix_bfrops_base_print_timeval
#define pmix_bfrops_base_print_uint                             pmix_bfrops_base_print_uint
#define pmix_bfrops_base_print_uint16                           pmix_bfrops_base_print_uint16
#define pmix_bfrops_base_print_uint32                           pmix_bfrops_base_print_uint32
#define pmix_bfrops_base_print_uint64                           pmix_bfrops_base_print_uint64
#define pmix_bfrops_base_print_uint8                            pmix_bfrops_base_print_uint8
#define pmix_bfrops_base_print_value                            pmix_bfrops_base_print_value
#define pmix_bfrops_base_std_copy                               pmix_bfrops_base_std_copy
#define pmix_bfrops_base_unpack                                 pmix_bfrops_base_unpack
#define pmix_bfrops_base_unpack_alloc_directive                 pmix_bfrops_base_unpack_alloc_directive
#define pmix_bfrops_base_unpack_app                             pmix_bfrops_base_unpack_app
#define pmix_bfrops_base_unpack_array                           pmix_bfrops_base_unpack_array
#define pmix_bfrops_base_unpack_bo                              pmix_bfrops_base_unpack_bo
#define pmix_bfrops_base_unpack_bool                            pmix_bfrops_base_unpack_bool
#define pmix_bfrops_base_unpack_buf                             pmix_bfrops_base_unpack_buf
#define pmix_bfrops_base_unpack_byte                            pmix_bfrops_base_unpack_byte
#define pmix_bfrops_base_unpack_cmd                             pmix_bfrops_base_unpack_cmd
#define pmix_bfrops_base_unpack_darray                          pmix_bfrops_base_unpack_darray
#define pmix_bfrops_base_unpack_datatype                        pmix_bfrops_base_unpack_datatype
#define pmix_bfrops_base_unpack_double                          pmix_bfrops_base_unpack_double
#define pmix_bfrops_base_unpack_float                           pmix_bfrops_base_unpack_float
#define pmix_bfrops_base_unpack_info                            pmix_bfrops_base_unpack_info
#define pmix_bfrops_base_unpack_info_directives                 pmix_bfrops_base_unpack_info_directives
#define pmix_bfrops_base_unpack_int                             pmix_bfrops_base_unpack_int
#define pmix_bfrops_base_unpack_int16                           pmix_bfrops_base_unpack_int16
#define pmix_bfrops_base_unpack_int32                           pmix_bfrops_base_unpack_int32
#define pmix_bfrops_base_unpack_int64                           pmix_bfrops_base_unpack_int64
#define pmix_bfrops_base_unpack_kval                            pmix_bfrops_base_unpack_kval
#define pmix_bfrops_base_unpack_modex                           pmix_bfrops_base_unpack_modex
#define pmix_bfrops_base_unpack_pdata                           pmix_bfrops_base_unpack_pdata
#define pmix_bfrops_base_unpack_persist                         pmix_bfrops_base_unpack_persist
#define pmix_bfrops_base_unpack_pid                             pmix_bfrops_base_unpack_pid
#define pmix_bfrops_base_unpack_pinfo                           pmix_bfrops_base_unpack_pinfo
#define pmix_bfrops_base_unpack_proc                            pmix_bfrops_base_unpack_proc
#define pmix_bfrops_base_unpack_pstate                          pmix_bfrops_base_unpack_pstate
#define pmix_bfrops_base_unpack_ptr                             pmix_bfrops_base_unpack_ptr
#define pmix_bfrops_base_unpack_query                           pmix_bfrops_base_unpack_query
#define pmix_bfrops_base_unpack_range                           pmix_bfrops_base_unpack_range
#define pmix_bfrops_base_unpack_rank                            pmix_bfrops_base_unpack_rank
#define pmix_bfrops_base_unpack_scope                           pmix_bfrops_base_unpack_scope
#define pmix_bfrops_base_unpack_sizet                           pmix_bfrops_base_unpack_sizet
#define pmix_bfrops_base_unpack_status                          pmix_bfrops_base_unpack_status
#define pmix_bfrops_base_unpack_string                          pmix_bfrops_base_unpack_string
#define pmix_bfrops_base_unpack_time                            pmix_bfrops_base_unpack_time
#define pmix_bfrops_base_unpack_timeval                         pmix_bfrops_base_unpack_timeval
#define pmix_bfrops_base_unpack_val                             pmix_bfrops_base_unpack_val
#define pmix_bfrops_base_unpack_value                           pmix_bfrops_base_unpack_value
#define pmix_bfrops_base_value_cmp                              pmix_bfrops_base_value_cmp
#define pmix_bfrops_base_value_load                             pmix_bfrops_base_value_load
#define pmix_bfrops_base_value_unload                           pmix_bfrops_base_value_unload
#define pmix_bfrops_base_value_xfer                             pmix_bfrops_base_value_xfer
#define pmix_bfrops_globals                                     pmix_bfrops_globals
#define pmix_bfrop_store_data_type                              pmix_bfrop_store_data_type
#define pmix_bfrop_too_small                                    pmix_bfrop_too_small
#define pmix_bfrop_type_info_t_class                            pmix_bfrop_type_info_t_class
#define pmix_buffer_t_class                                     pmix_buffer_t_class
#define pmix_cb_t_class                                         pmix_cb_t_class
#define pmix_class_finalize                                     pmix_class_finalize
#define pmix_class_init_epoch                                   pmix_class_init_epoch
#define pmix_class_initialize                                   pmix_class_initialize
#define pmix_client_globals                                     pmix_client_globals
#define pmix_cmd_line_add                                       pmix_cmd_line_add
#define pmix_cmd_line_create                                    pmix_cmd_line_create
#define pmix_cmd_line_get_argc                                  pmix_cmd_line_get_argc
#define pmix_cmd_line_get_argv                                  pmix_cmd_line_get_argv
#define pmix_cmd_line_get_ninsts                                pmix_cmd_line_get_ninsts
#define pmix_cmd_line_get_param                                 pmix_cmd_line_get_param
#define pmix_cmd_line_get_tail                                  pmix_cmd_line_get_tail
#define pmix_cmd_line_get_usage_msg                             pmix_cmd_line_get_usage_msg
#define pmix_cmd_line_is_taken                                  pmix_cmd_line_is_taken
#define pmix_cmd_line_make_opt3                                 pmix_cmd_line_make_opt3
#define pmix_cmd_line_make_opt_mca                              pmix_cmd_line_make_opt_mca
#define pmix_cmd_line_parse                                     pmix_cmd_line_parse
#define pmix_cmd_line_t_class                                   pmix_cmd_line_t_class
#define pmix_command_string                                     pmix_command_string
#define PMIx_Commit                                             PMIx_Commit
#define PMIx_Connect                                            PMIx_Connect
#define PMIx_Connect_nb                                         PMIx_Connect_nb
#define PMIx_Data_copy                                          PMIx_Data_copy
#define PMIx_Data_copy_payload                                  PMIx_Data_copy_payload
#define PMIx_Data_pack                                          PMIx_Data_pack
#define PMIx_Data_print                                         PMIx_Data_print
#define PMIx_Data_range_string                                  PMIx_Data_range_string
#define PMIx_Data_type_string                                   PMIx_Data_type_string
#define PMIx_Data_unpack                                        PMIx_Data_unpack
#define pmix_debug_threads                                      pmix_debug_threads
#define PMIx_Deregister_event_handler                           PMIx_Deregister_event_handler
#define pmix_deregister_params                                  pmix_deregister_params
#define pmix_dirname                                            pmix_dirname
#define PMIx_Disconnect                                         PMIx_Disconnect
#define PMIx_Disconnect_nb                                      PMIx_Disconnect_nb
#define pmix_environ_merge                                      pmix_environ_merge
#define PMIx_Error_string                                       PMIx_Error_string
#define pmix_fd_read                                            pmix_fd_read
#define pmix_fd_set_cloexec                                     pmix_fd_set_cloexec
#define pmix_fd_write                                           pmix_fd_write
#define PMIx_Fence                                              PMIx_Fence
#define PMIx_Fence_nb                                           PMIx_Fence_nb
#define PMIx_Finalize                                           PMIx_Finalize
#define pmix_find_absolute_path                                 pmix_find_absolute_path
#define pmix_gds_base_assign_module                             pmix_gds_base_assign_module
#define pmix_gds_base_framework                                 pmix_gds_base_framework
#define pmix_gds_base_get_available_modules                     pmix_gds_base_get_available_modules
#define pmix_gds_base_output                                    pmix_gds_base_output
#define pmix_gds_base_select                                    pmix_gds_base_select
#define pmix_gds_base_setup_fork                                pmix_gds_base_setup_fork
#define pmix_gds_globals                                        pmix_gds_globals
#define PMIx_generate_ppn                                       PMIx_generate_ppn
#define PMIx_generate_regex                                     PMIx_generate_regex
#define PMIx_Get                                                PMIx_Get
#define PMIx_Get_nb                                             PMIx_Get_nb
#define PMIx_Get_version                                        PMIx_Get_version
#define pmix_global_lock                                        pmix_global_lock
#define pmix_globals                                            pmix_globals
#define pmix_hash_fetch                                         pmix_hash_fetch
#define pmix_hash_fetch_by_key                                  pmix_hash_fetch_by_key
#define pmix_hash_remove_data                                   pmix_hash_remove_data
#define pmix_hash_store                                         pmix_hash_store
#define pmix_hash_table_get_first_key_ptr                       pmix_hash_table_get_first_key_ptr
#define pmix_hash_table_get_first_key_uint32                    pmix_hash_table_get_first_key_uint32
#define pmix_hash_table_get_first_key_uint64                    pmix_hash_table_get_first_key_uint64
#define pmix_hash_table_get_next_key_ptr                        pmix_hash_table_get_next_key_ptr
#define pmix_hash_table_get_next_key_uint32                     pmix_hash_table_get_next_key_uint32
#define pmix_hash_table_get_next_key_uint64                     pmix_hash_table_get_next_key_uint64
#define pmix_hash_table_get_value_ptr                           pmix_hash_table_get_value_ptr
#define pmix_hash_table_get_value_uint32                        pmix_hash_table_get_value_uint32
#define pmix_hash_table_get_value_uint64                        pmix_hash_table_get_value_uint64
#define pmix_hash_table_init                                    pmix_hash_table_init
#define pmix_hash_table_init2                                   pmix_hash_table_init2
#define pmix_hash_table_remove_all                              pmix_hash_table_remove_all
#define pmix_hash_table_remove_value_ptr                        pmix_hash_table_remove_value_ptr
#define pmix_hash_table_remove_value_uint32                     pmix_hash_table_remove_value_uint32
#define pmix_hash_table_remove_value_uint64                     pmix_hash_table_remove_value_uint64
#define pmix_hash_table_set_value_ptr                           pmix_hash_table_set_value_ptr
#define pmix_hash_table_set_value_uint32                        pmix_hash_table_set_value_uint32
#define pmix_hash_table_set_value_uint64                        pmix_hash_table_set_value_uint64
#define pmix_hash_table_t_class                                 pmix_hash_table_t_class
#define pmix_home_directory                                     pmix_home_directory
#define pmix_host_server                                        pmix_host_server
#define pmix_hotel_init                                         pmix_hotel_init
#define pmix_ifaddrtokindex                                     pmix_ifaddrtokindex
#define pmix_ifaddrtoname                                       pmix_ifaddrtoname
#define pmix_ifbegin                                            pmix_ifbegin
#define pmix_ifcount                                            pmix_ifcount
#define pmix_ifgetaliases                                       pmix_ifgetaliases
#define pmix_ifindextoaddr                                      pmix_ifindextoaddr
#define pmix_ifindextoflags                                     pmix_ifindextoflags
#define pmix_ifindextokindex                                    pmix_ifindextokindex
#define pmix_ifindextomac                                       pmix_ifindextomac
#define pmix_ifindextomask                                      pmix_ifindextomask
#define pmix_ifindextomtu                                       pmix_ifindextomtu
#define pmix_ifindextoname                                      pmix_ifindextoname
#define pmix_ifislocal                                          pmix_ifislocal
#define pmix_ifisloopback                                       pmix_ifisloopback
#define pmix_ifkindextoaddr                                     pmix_ifkindextoaddr
#define pmix_ifkindextoname                                     pmix_ifkindextoname
#define pmix_ifmatches                                          pmix_ifmatches
#define pmix_ifnametoaddr                                       pmix_ifnametoaddr
#define pmix_ifnametoindex                                      pmix_ifnametoindex
#define pmix_ifnametokindex                                     pmix_ifnametokindex
#define pmix_ifnext                                             pmix_ifnext
#define pmix_iftupletoaddr                                      pmix_iftupletoaddr
#define pmix_info_caddy_t_class                                 pmix_info_caddy_t_class
#define PMIx_Info_directives_string                             PMIx_Info_directives_string
#define PMIx_Init                                               PMIx_Init
#define pmix_init_called                                        pmix_init_called
#define pmix_initialized                                        pmix_initialized
#define PMIx_Initialized                                        PMIx_Initialized
#define PMIx_Job_control_nb                                     PMIx_Job_control_nb
#define pmix_kval_t_class                                       pmix_kval_t_class
#define pmix_listener_t_class                                   pmix_listener_t_class
#define pmix_list_item_t_class                                  pmix_list_item_t_class
#define pmix_list_t_class                                       pmix_list_t_class
#define PMIx_Log_nb                                             PMIx_Log_nb
#define PMIx_Lookup                                             PMIx_Lookup
#define PMIx_Lookup_nb                                          PMIx_Lookup_nb
#define pmix_mca_base_close                                     pmix_mca_base_close
#define pmix_mca_base_cmd_line_process_args                     pmix_mca_base_cmd_line_process_args
#define pmix_mca_base_cmd_line_setup                            pmix_mca_base_cmd_line_setup
#define pmix_mca_base_cmd_line_wrap_args                        pmix_mca_base_cmd_line_wrap_args
#define pmix_mca_base_component_close                           pmix_mca_base_component_close
#define pmix_mca_base_component_compare                         pmix_mca_base_component_compare
#define pmix_mca_base_component_compare_priority                pmix_mca_base_component_compare_priority
#define pmix_mca_base_component_compatible                      pmix_mca_base_component_compatible
#define pmix_mca_base_component_disable_dlopen                  pmix_mca_base_component_disable_dlopen
#define pmix_mca_base_component_find                            pmix_mca_base_component_find
#define pmix_mca_base_component_find_finalize                   pmix_mca_base_component_find_finalize
#define pmix_mca_base_component_list_item_t_class               pmix_mca_base_component_list_item_t_class
#define pmix_mca_base_component_parse_requested                 pmix_mca_base_component_parse_requested
#define pmix_mca_base_component_path                            pmix_mca_base_component_path
#define pmix_mca_base_component_priority_list_item_t_class      pmix_mca_base_component_priority_list_item_t_class
#define pmix_mca_base_component_repository_add                  pmix_mca_base_component_repository_add
#define pmix_mca_base_component_repository_finalize             pmix_mca_base_component_repository_finalize
#define pmix_mca_base_component_repository_get_components       pmix_mca_base_component_repository_get_components
#define pmix_mca_base_component_repository_init                 pmix_mca_base_component_repository_init
#define pmix_mca_base_component_repository_item_t_class         pmix_mca_base_component_repository_item_t_class
#define pmix_mca_base_component_repository_open                 pmix_mca_base_component_repository_open
#define pmix_mca_base_component_repository_release              pmix_mca_base_component_repository_release
#define pmix_mca_base_component_repository_retain_component     pmix_mca_base_component_repository_retain_component
#define pmix_mca_base_components_close                          pmix_mca_base_components_close
#define pmix_mca_base_components_filter                         pmix_mca_base_components_filter
#define pmix_mca_base_component_show_load_errors                pmix_mca_base_component_show_load_errors
#define pmix_mca_base_component_to_string                       pmix_mca_base_component_to_string
#define pmix_mca_base_component_track_load_errors               pmix_mca_base_component_track_load_errors
#define pmix_mca_base_component_unload                          pmix_mca_base_component_unload
#define pmix_mca_base_component_var_register                    pmix_mca_base_component_var_register
#define pmix_mca_base_failed_component_t_class                  pmix_mca_base_failed_component_t_class
#define pmix_mca_base_framework_close                           pmix_mca_base_framework_close
#define pmix_mca_base_framework_components_close                pmix_mca_base_framework_components_close
#define pmix_mca_base_framework_components_open                 pmix_mca_base_framework_components_open
#define pmix_mca_base_framework_components_register             pmix_mca_base_framework_components_register
#define pmix_mca_base_framework_is_open                         pmix_mca_base_framework_is_open
#define pmix_mca_base_framework_is_registered                   pmix_mca_base_framework_is_registered
#define pmix_mca_base_framework_open                            pmix_mca_base_framework_open
#define pmix_mca_base_framework_register                        pmix_mca_base_framework_register
#define pmix_mca_base_framework_var_register                    pmix_mca_base_framework_var_register
#define pmix_mca_base_open                                      pmix_mca_base_open
#define pmix_mca_base_select                                    pmix_mca_base_select
#define pmix_mca_base_system_default_path                       pmix_mca_base_system_default_path
#define pmix_mca_base_user_default_path                         pmix_mca_base_user_default_path
#define pmix_mca_base_var_build_env                             pmix_mca_base_var_build_env
#define pmix_mca_base_var_cache_files                           pmix_mca_base_var_cache_files
#define pmix_mca_base_var_check_exclusive                       pmix_mca_base_var_check_exclusive
#define pmix_mca_base_var_deregister                            pmix_mca_base_var_deregister
#define pmix_mca_base_var_dump                                  pmix_mca_base_var_dump
#define pmix_mca_base_var_env_name                              pmix_mca_base_var_env_name
#define pmix_mca_base_var_finalize                              pmix_mca_base_var_finalize
#define pmix_mca_base_var_find                                  pmix_mca_base_var_find
#define pmix_mca_base_var_find_by_name                          pmix_mca_base_var_find_by_name
#define pmix_mca_base_var_get                                   pmix_mca_base_var_get
#define pmix_mca_base_var_get_count                             pmix_mca_base_var_get_count
#define pmix_mca_base_var_get_value                             pmix_mca_base_var_get_value
#define pmix_mca_base_var_group_component_register              pmix_mca_base_var_group_component_register
#define pmix_mca_base_var_group_deregister                      pmix_mca_base_var_group_deregister
#define pmix_mca_base_var_group_find                            pmix_mca_base_var_group_find
#define pmix_mca_base_var_group_find_by_name                    pmix_mca_base_var_group_find_by_name
#define pmix_mca_base_var_group_get                             pmix_mca_base_var_group_get
#define pmix_mca_base_var_group_get_count                       pmix_mca_base_var_group_get_count
#define pmix_mca_base_var_group_get_stamp                       pmix_mca_base_var_group_get_stamp
#define pmix_mca_base_var_group_register                        pmix_mca_base_var_group_register
#define pmix_mca_base_var_group_set_var_flag                    pmix_mca_base_var_group_set_var_flag
#define pmix_mca_base_var_group_t_class                         pmix_mca_base_var_group_t_class
#define pmix_mca_base_var_init                                  pmix_mca_base_var_init
#define pmix_mca_base_var_process_env_list                      pmix_mca_base_var_process_env_list
#define pmix_mca_base_var_process_env_list_from_file            pmix_mca_base_var_process_env_list_from_file
#define pmix_mca_base_var_register                              pmix_mca_base_var_register
#define pmix_mca_base_var_register_synonym                      pmix_mca_base_var_register_synonym
#define pmix_mca_base_var_set_flag                              pmix_mca_base_var_set_flag
#define pmix_mca_base_var_set_value                             pmix_mca_base_var_set_value
#define pmix_mca_base_var_t_class                               pmix_mca_base_var_t_class
#define pmix_mutex_t_class                                      pmix_mutex_t_class
#define pmix_namelist_t_class                                   pmix_namelist_t_class
#define pmix_net_addr_isipv4public                              pmix_net_addr_isipv4public
#define pmix_net_finalize                                       pmix_net_finalize
#define pmix_net_get_hostname                                   pmix_net_get_hostname
#define pmix_net_get_port                                       pmix_net_get_port
#define pmix_net_init                                           pmix_net_init
#define pmix_net_isaddr                                         pmix_net_isaddr
#define pmix_net_islocalhost                                    pmix_net_islocalhost
#define pmix_net_prefix2netmask                                 pmix_net_prefix2netmask
#define pmix_net_samenetwork                                    pmix_net_samenetwork
#define PMIx_Notify_event                                       PMIx_Notify_event
#define pmix_nspace_caddy_t_class                               pmix_nspace_caddy_t_class
#define pmix_nspace_t_class                                     pmix_nspace_t_class
#define pmix_object_t_class                                     pmix_object_t_class
#define pmix_os_path                                            pmix_os_path
#define pmix_output                                             pmix_output
#define pmix_output_close                                       pmix_output_close
#define pmix_output_finalize                                    pmix_output_finalize
#define pmix_output_get_verbosity                               pmix_output_get_verbosity
#define pmix_output_hexdump                                     pmix_output_hexdump
#define pmix_output_init                                        pmix_output_init
#define pmix_output_open                                        pmix_output_open
#define pmix_output_reopen                                      pmix_output_reopen
#define pmix_output_reopen_all                                  pmix_output_reopen_all
#define pmix_output_set_output_file_info                        pmix_output_set_output_file_info
#define pmix_output_set_verbosity                               pmix_output_set_verbosity
#define pmix_output_switch                                      pmix_output_switch
#define pmix_output_verbose                                     pmix_output_verbose
#define pmix_output_vverbose                                    pmix_output_vverbose
#define pmix_path_access                                        pmix_path_access
#define pmix_path_df                                            pmix_path_df
#define pmix_path_find                                          pmix_path_find
#define pmix_path_findv                                         pmix_path_findv
#define pmix_path_is_absolute                                   pmix_path_is_absolute
#define pmix_path_nfs                                           pmix_path_nfs
#define pmix_pdl_base_framework                                 pmix_pdl_base_framework
#define pmix_peer_t_class                                       pmix_peer_t_class
#define pmix_pending_connection_t_class                         pmix_pending_connection_t_class
#define PMIx_Persistence_string                                 PMIx_Persistence_string
#define pmix_pif_base_framework                                 pmix_pif_base_framework
#define pmix_pinstall_dirs                                      pmix_pinstall_dirs
#define pmix_pinstalldirs_base_framework                        pmix_pinstalldirs_base_framework
#define pmix_pnet                                               pmix_pnet
#define pmix_pnet_base_child_finalized                          pmix_pnet_base_child_finalized
#define pmix_pnet_base_framework                                pmix_pnet_base_framework
#define pmix_pnet_base_local_app_finalized                      pmix_pnet_base_local_app_finalized
#define pmix_pnet_base_select                                   pmix_pnet_base_select
#define pmix_pnet_base_setup_app                                pmix_pnet_base_setup_app
#define pmix_pnet_base_setup_fork                               pmix_pnet_base_setup_fork
#define pmix_pnet_base_setup_local_network                      pmix_pnet_base_setup_local_network
#define pmix_pnet_globals                                       pmix_pnet_globals
#define pmix_pointer_array_add                                  pmix_pointer_array_add
#define pmix_pointer_array_init                                 pmix_pointer_array_init
#define pmix_pointer_array_set_item                             pmix_pointer_array_set_item
#define pmix_pointer_array_set_size                             pmix_pointer_array_set_size
#define pmix_pointer_array_t_class                              pmix_pointer_array_t_class
#define pmix_pointer_array_test_and_set_item                    pmix_pointer_array_test_and_set_item
#define pmix_preg                                               pmix_preg
#define pmix_preg_base_framework                                pmix_preg_base_framework
#define pmix_preg_base_generate_node_regex                      pmix_preg_base_generate_node_regex
#define pmix_preg_base_generate_ppn                             pmix_preg_base_generate_ppn
#define pmix_preg_base_parse_nodes                              pmix_preg_base_parse_nodes
#define pmix_preg_base_parse_procs                              pmix_preg_base_parse_procs
#define pmix_preg_base_resolve_nodes                            pmix_preg_base_resolve_nodes
#define pmix_preg_base_resolve_peers                            pmix_preg_base_resolve_peers
#define pmix_preg_base_select                                   pmix_preg_base_select
#define pmix_preg_globals                                       pmix_preg_globals
#define PMIx_Process_monitor_nb                                 PMIx_Process_monitor_nb
#define PMIx_Proc_state_string                                  PMIx_Proc_state_string
#define pmix_psec_base_assign_module                            pmix_psec_base_assign_module
#define pmix_psec_base_framework                                pmix_psec_base_framework
#define pmix_psec_base_get_available_modules                    pmix_psec_base_get_available_modules
#define pmix_psec_base_select                                   pmix_psec_base_select
#define pmix_psensor                                            pmix_psensor
#define pmix_psensor_base                                       pmix_psensor_base
#define pmix_psensor_base_framework                             pmix_psensor_base_framework
#define pmix_psensor_base_select                                pmix_psensor_base_select
#define pmix_psensor_base_start                                 pmix_psensor_base_start
#define pmix_psensor_base_stop                                  pmix_psensor_base_stop
#define pmix_pshmem                                             pmix_pshmem
#define pmix_pshmem_base_framework                              pmix_pshmem_base_framework
#define pmix_pshmem_base_select                                 pmix_pshmem_base_select
#define pmix_ptl_base_assign_module                             pmix_ptl_base_assign_module
#define pmix_ptl_base_cancel_recv                               pmix_ptl_base_cancel_recv
#define pmix_ptl_base_connect                                   pmix_ptl_base_connect
#define pmix_ptl_base_connect_to_peer                           pmix_ptl_base_connect_to_peer
#define pmix_ptl_base_framework                                 pmix_ptl_base_framework
#define pmix_ptl_base_get_available_modules                     pmix_ptl_base_get_available_modules
#define pmix_ptl_base_lost_connection                           pmix_ptl_base_lost_connection
#define pmix_ptl_base_output                                    pmix_ptl_base_output
#define pmix_ptl_base_process_msg                               pmix_ptl_base_process_msg
#define pmix_ptl_base_recv_blocking                             pmix_ptl_base_recv_blocking
#define pmix_ptl_base_recv_handler                              pmix_ptl_base_recv_handler
#define pmix_ptl_base_register_recv                             pmix_ptl_base_register_recv
#define pmix_ptl_base_select                                    pmix_ptl_base_select
#define pmix_ptl_base_send                                      pmix_ptl_base_send
#define pmix_ptl_base_send_blocking                             pmix_ptl_base_send_blocking
#define pmix_ptl_base_send_handler                              pmix_ptl_base_send_handler
#define pmix_ptl_base_send_recv                                 pmix_ptl_base_send_recv
#define pmix_ptl_base_set_blocking                              pmix_ptl_base_set_blocking
#define pmix_ptl_base_set_nonblocking                           pmix_ptl_base_set_nonblocking
#define pmix_ptl_base_set_notification_cbfunc                   pmix_ptl_base_set_notification_cbfunc
#define pmix_ptl_base_start_listening                           pmix_ptl_base_start_listening
#define pmix_ptl_base_stop_listening                            pmix_ptl_base_stop_listening
#define pmix_ptl_globals                                        pmix_ptl_globals
#define pmix_ptl_posted_recv_t_class                            pmix_ptl_posted_recv_t_class
#define pmix_ptl_queue_t_class                                  pmix_ptl_queue_t_class
#define pmix_ptl_recv_t_class                                   pmix_ptl_recv_t_class
#define pmix_ptl_send_t_class                                   pmix_ptl_send_t_class
#define pmix_ptl_sr_t_class                                     pmix_ptl_sr_t_class
#define PMIx_Publish                                            PMIx_Publish
#define PMIx_Publish_nb                                         PMIx_Publish_nb
#define PMIx_Put                                                PMIx_Put
#define pmix_query_caddy_t_class                                pmix_query_caddy_t_class
#define PMIx_Query_info_nb                                      PMIx_Query_info_nb
#define pmix_rand                                               pmix_rand
#define pmix_random                                             pmix_random
#define pmix_rank_info_t_class                                  pmix_rank_info_t_class
#define pmix_recursive_mutex_t_class                            pmix_recursive_mutex_t_class
#define pmix_regex_range_t_class                                pmix_regex_range_t_class
#define pmix_regex_value_t_class                                pmix_regex_value_t_class
#define PMIx_Register_event_handler                             PMIx_Register_event_handler
#define pmix_register_params                                    pmix_register_params
#define PMIx_Resolve_nodes                                      PMIx_Resolve_nodes
#define PMIx_Resolve_peers                                      PMIx_Resolve_peers
#define pmix_ring_buffer_init                                   pmix_ring_buffer_init
#define pmix_ring_buffer_poke                                   pmix_ring_buffer_poke
#define pmix_ring_buffer_pop                                    pmix_ring_buffer_pop
#define pmix_ring_buffer_push                                   pmix_ring_buffer_push
#define pmix_rte_finalize                                       pmix_rte_finalize
#define pmix_rte_init                                           pmix_rte_init
#define PMIx_Scope_string                                       PMIx_Scope_string
#define PMIx_server_deregister_client                           PMIx_server_deregister_client
#define PMIx_server_deregister_nspace                           PMIx_server_deregister_nspace
#define PMIx_server_dmodex_request                              PMIx_server_dmodex_request
#define PMIx_server_finalize                                    PMIx_server_finalize
#define pmix_server_globals                                     pmix_server_globals
#define PMIx_server_init                                        PMIx_server_init
#define PMIx_server_register_client                             PMIx_server_register_client
#define PMIx_server_register_nspace                             PMIx_server_register_nspace
#define PMIx_server_setup_application                           PMIx_server_setup_application
#define PMIx_server_setup_fork                                  PMIx_server_setup_fork
#define PMIx_server_setup_local_support                         PMIx_server_setup_local_support
#define pmix_setenv                                             pmix_setenv
#define pmix_setup_caddy_t_class                                pmix_setup_caddy_t_class
#define pmix_shift_caddy_t_class                                pmix_shift_caddy_t_class
#define pmix_show_help                                          pmix_show_help
#define pmix_show_help_add_dir                                  pmix_show_help_add_dir
#define pmix_show_help_finalize                                 pmix_show_help_finalize
#define pmix_show_help_init                                     pmix_show_help_init
#define pmix_show_help_string                                   pmix_show_help_string
#define pmix_show_help_vstring                                  pmix_show_help_vstring
#define pmix_show_vhelp                                         pmix_show_vhelp
#define pmix_snprintf                                           pmix_snprintf
#define PMIx_Spawn                                              PMIx_Spawn
#define PMIx_Spawn_nb                                           PMIx_Spawn_nb
#define pmix_srand                                              pmix_srand
#define PMIx_Store_internal                                     PMIx_Store_internal
#define pmix_sync_wait_mt                                       pmix_sync_wait_mt
#define pmix_thread_get_self                                    pmix_thread_get_self
#define pmix_thread_join                                        pmix_thread_join
#define pmix_thread_kill                                        pmix_thread_kill
#define pmix_thread_self_compare                                pmix_thread_self_compare
#define pmix_thread_set_main                                    pmix_thread_set_main
#define pmix_thread_start                                       pmix_thread_start
#define pmix_thread_t_class                                     pmix_thread_t_class
#define pmix_tmp_directory                                      pmix_tmp_directory
#define PMIx_tool_finalize                                      PMIx_tool_finalize
#define PMIx_tool_init                                          PMIx_tool_init
#define pmix_tsd_key_create                                     pmix_tsd_key_create
#define pmix_tsd_keys_destruct                                  pmix_tsd_keys_destruct
#define PMIx_Unpublish                                          PMIx_Unpublish
#define PMIx_Unpublish_nb                                       PMIx_Unpublish_nb
#define pmix_unsetenv                                           pmix_unsetenv
#define pmix_util_compress_string                               pmix_util_compress_string
#define pmix_util_getid                                         pmix_util_getid
#define pmix_util_get_ranges                                    pmix_util_get_ranges
#define pmix_util_keyval_parse                                  pmix_util_keyval_parse
#define pmix_util_keyval_parse_finalize                         pmix_util_keyval_parse_finalize
#define pmix_util_keyval_parse_init                             pmix_util_keyval_parse_init
#define pmix_util_keyval_parse_lineno                           pmix_util_keyval_parse_lineno
#define pmix_util_keyval_save_internal_envars                   pmix_util_keyval_save_internal_envars
#define pmix_util_parse_range_options                           pmix_util_parse_range_options
#define pmix_util_uncompress_string                             pmix_util_uncompress_string
#define pmix_value_array_set_size                               pmix_value_array_set_size
#define pmix_value_array_t_class                                pmix_value_array_t_class
#define pmix_value_load                                         pmix_value_load
#define pmix_value_xfer                                         pmix_value_xfer
#define pmix_var_type_names                                     pmix_var_type_names
#define pmix_vasprintf                                          pmix_vasprintf
#define pmix_vsnprintf                                          pmix_vsnprintf
